init

diff --git a/teamsapp.local.yml b/teamsapp.local.yml
--- a/teamsapp.local.yml
+++ b/teamsapp.local.yml
@@ -16,24 +16,30 @@ provision:
       tenantId: AAD_APP_TENANT_ID
       authority: AAD_APP_OAUTH_AUTHORITY
       authorityHost: AAD_APP_OAUTH_AUTHORITY_HOST
+  # - uses: script
+  #   with:
+  #     run: |
+  #       for ($i = 1; $i -le 3; $i++) {
+  #         $endpoint = (Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels" | Select-String -Pattern 'https://[a-zA-Z0-9 -\.]*\.ngrok-free\.app').Matches.Value
+  #         if ($endpoint) {
+  #           break
+  #         }
+  #         sleep 3
+  #       }
+  #       if (-not $endpoint) {
+  #         echo "ERROR: Failed to find tunnel endpoint after 3 attempts."
+  #         exit 1
+  #       } else {
+  #         echo "::set-teamsfx-env TAB_APP_ID=${{AAD_APP_CLIENT_ID}}"
+  #         echo "::set-teamsfx-env PUBLIC_HOSTNAME=$($endpoint.Substring(8))"
+  #         echo "::set-teamsfx-env TAB_APP_URI=api://$($endpoint.Substring(8))/${{AAD_APP_CLIENT_ID}}"
+  #       }
   - uses: script
     with:
       run: |
-        for ($i = 1; $i -le 3; $i++) {
-          $endpoint = (Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels" | Select-String -Pattern 'https://[a-zA-Z0-9 -\.]*\.ngrok-free\.app').Matches.Value
-          if ($endpoint) {
-            break
-          }
-          sleep 3
-        }
-        if (-not $endpoint) {
-          echo "ERROR: Failed to find tunnel endpoint after 3 attempts."
-          exit 1
-        } else {
-          echo "::set-teamsfx-env TAB_APP_ID=${{AAD_APP_CLIENT_ID}}"
-          echo "::set-teamsfx-env PUBLIC_HOSTNAME=$($endpoint.Substring(8))"
-          echo "::set-teamsfx-env TAB_APP_URI=api://$($endpoint.Substring(8))/${{AAD_APP_CLIENT_ID}}"
-        }
+        echo "::set-teamsfx-env TAB_APP_ID=${{AAD_APP_CLIENT_ID}}"
+        echo "::set-teamsfx-env PUBLIC_HOSTNAME=localhost:53000"
+        echo "::set-teamsfx-env TAB_APP_URI=api://localhost:53000/${{AAD_APP_CLIENT_ID}}"
   - uses: teamsApp/create # Creates a Teams app
     with:
       name: yotabsso-${{TEAMSFX_ENV}} # Teams app name
